import Head from 'next/head';
import HomePage from '../src/components/home/HomePage';

export default function Home() {
    return (
        <div className='page'>
            <Head>
                <title>Kidala upload</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomePage />
        </div>
    );
}
